### ISSUE TITLE
Local build doesn't work

### ISSUE THREAD

**Issue by cristi-neagu** [expilu/sailaway-api-to-nmea#4]
Hello,

If i try to build the solution locally, i get Sailaway API errors. But the downloaded version works properly. Is the source on GitHub up to date?

Thank you.

**Comment by expilu** [comment]
That's because you need an API key.
You need to input the API key here: https://github.com/expilu/sailaway-api-to-nmea/blob/91a86e9f55d0b7e3524efc22f6b3778c13ebc743/SailawayToNMEA/App/Conf.cs#L6

The version I distribute has an API key provided to me. You need to reach the developer of the game to have your own.
