### ISSUE TITLE
qtvlm AIS issue

### ISSUE THREAD

**Issue by maitaivw** [expilu/sailaway-api-to-nmea#6]
Hi, I am Philippe Lelong, one of the developer of qtVlm. We have one issue with your interface concerning AIS internet feed, can you please contact us?
Thanks
maitai < at > virtual-winds.org

**Comment by xavseq** [comment]
Hi, 
Long time user, but since your mods I keep getting an error.
If you cannot see the picture below, it says
"Sailaway connection problem: Track AllBoats Error:{sorry }
Check if your API key is set correctly

Thanks for this great little tool, I hope it can be fixed?
tchau

![image](https://user-images.githubusercontent.com/65097859/81488407-fcac7180-929a-11ea-8000-8070c587d5f7.png)

**Comment by xavseq** [comment]
Hi,

Your version 1.2 sorted out the issue 
Thanks
